name: kliniktap
description: "KlinikTap - Dasbor Telekonsultasi & Peresepan Digital"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock/
    - assets/images/
